# set base image (host OS)
FROM python:3.10-slim-buster
ENV HTTP_SERVER=""
ENV DEVICE_NAME=""
ENV CLEAN_RESTART=""
ENV DISABLE_ACI=""
ENV SEND_SYSTEM_STATS=""

#Local dependencies for cv2
RUN #curl --silent --location https://deb.nodesource.com/setup_0.10 | bash -
RUN apt-get update
RUN #apt-get upgrade
RUN apt-get install gcc python3-dev graphviz -y
RUN apt-get install ffmpeg libsm6 libxext6  -y
#

# set the working directory in the container
WORKDIR /src/

# copy the content of the local directory to the working directory
COPY services/CV /src/
COPY detector /src/
COPY consumption /src/

# install dependencies
RUN pip install -r requirements.txt

# command to run on container start
CMD [ "python", "./starter.py" ]